### ISSUE TITLE
[TASK] CI, find out variables used to run a test, when the test initiated from the web interface

### ISSUE THREAD

**Issue by RanRegev** [prplfoundation/prplMesh#1007]
**A way to trace back the values of variables, e.g. TEST_TO_RUN, when running CI pipelines from the web interface (https://gitlab.com/prpl-foundation/prplMesh/pipelines/new)**
- Looking at tests results and relying on the good will of the initiator (even if it is you) to remember what were the values, is not a good practice. You may be solving a non-problem or looking at output that does not match your expectations.

**Alternatives**
- Running from the command line has both the command line history AND a web presentation of the variables.
- Splitting the tests into non-variable commands. Each test on its own.

**Additional context**
The problem occurred to me the first time I tried to run a test.
I couldn't verify I ran it correctly.

**Comment by arnout** [comment]
So, what's the plan here... Do we add a job that prints all variables? Or maybe just in the jobs where it's relevant (probably only run-certification-tests, maybe .test-on-target as well) print the variables in an after_script.

**Comment by rmelotte** [comment]
I think the problem is mainly for the jobs where the user has to specify a variable manually, so currently only run-certification-tests.
We could print the values of TESTS_TO_RUN and DEVICE_UNDER_TEST before the test begins, but splitting the tests between separate jobs would probably make it even more clear.
