### ISSUE TITLE
[BUG] ieee1905_transport: Not tracking WLAN VAP interfaces

### ISSUE THREAD

**Issue by tomereli** [prplfoundation/prplMesh#1137]
**Describe the bug** -
When prplmesh is started, all WLAN VAP interfaces (wlan0.0, wlan2.0, etc.) are registered by transport using their ifindex.
During autoconfiguration, the VAP interfaces are removed and brought back up by the driver, causing their ifindex to change, therefore not to be tracked anymore by the transport.
This means that any 1905 messages received on the wireless bAPs are simply not handled by the ieee1905 transport service and therefore never get to their destination.

## Steps to reproduce

1. Build branch `dev/bap-wps-onboarding`
2. Run controller & agent
3. See in `/tmp/beerocks/logs/transport.log` that the interface index changes and are ignored

## Expected behavior

The ieee1905 transport should pick up any interface index changes and continue monitoring them.

Logs Attached -
[transport.log](https://github.com/prplfoundation/prplMesh/files/4468612/transport.log)

**Comment by tomereli** [comment]
[transport.log](https://github.com/prplfoundation/prplMesh/files/4468593/transport.log)

**Comment by arnout** [comment]
This touches upon a bigger architectural question. We need to identify interfaces in multiple places, and we have to keep several lists of interfaces.

- Interfaces that are used by transport.
  - Ideally there should be two sets of those: interfaces that are considered secure, and interfaces that are considered insecure. On the insecure interfaces, we should *only* do topology discovery, and allow a subset of incoming message types. In particular, we should *not* do autoconfig on the insecure interfaces.
  - Ideally the transport should send explicitly on individual interfaces rather than relying on the bridge. This is necessary for the concept of insecure interfaces, and also because not all interfaces are necessarily on the bridge. For example, if we implement switching between wired and wireless backhaul, the "inactive" interface should not be put in the bridge until the switch has completed, to avoid creating a loop.
  - When containers are used in the router (and this *will happen* in upcoming routers), virtual interfaces will be added to the bridge to communicate with these containers. Since whatever is inside the container is considered to be part of the device, we should probably not send anything on those interfaces. However, since the container will most likely not contain a 1905.1 entity, it doesn't matter much - anything we send to it will be ignored.
  - When a new interface appears (or when a new interface is added to the bridge), it should be added to the interface list. Or maybe not. I'm actually not very sure what the possible use cases are here - except for when a VAP is enabled. Actually, VAPs which are not active should also not be in this list, and I don't think they are since hostapd doesn't create the interface, right?
  - A special case of the above is for bAP. At least in the cfg80211 implementation. In 4addr mode, when a STA connects, a new interface `wlan0.1_staN` is created. So the transport should be aware of this. I believe hostapd automatically creates a bridge that joins all the per-STA interfaces, but due to the ebtables rule that bridge will not be used for the multicast messages.
  - Note that in general it is possible for interfaces to change name over their lifetime. In the OpenWrt web interface, for example, it is possible to change the name of any wired or wireless interface, and this is reflected in the name as seen in `ifr_name` in the various ioctls.
- Interfaces that are used in Topology Response and Link Metrics.
  - These don't necessarily need to be the same as the interfaces used by transport.
  - In particular, each of these has to have a unique MAC address - which generally is not the case e.g. for switch interfaces, or the per-STA interfaces created in 4addr mode.
  - The EasyMesh test plan only requires one interface for the backhaul.
  - We can actually get away with a single interface, for the bridge, which is what is currently implemented. Everything wireless has separate messages so doesn't need to be included in Link Metrics.
  - Even if we consider the bridge as the single interface, it would still be good to keep track of the interface on which each neighbour is connected, since that allows us to report more accurate link metrics - the neighbour can be used to identify the actual interface. For example, if we have a four-port switch with a single MAC address, and on two of the ports there's a direct connection to two other MultiAP devices, then we can distinguish the two ports based on the neighbour rather than the port MAC address.
- Interfaces managed by backhaul manager.
  - In general, the backhaul manager will manage (i.e. switch between) several interface: a bSTA interface on each radio, plus one or more wired interfaces.
  - When such an interface is brought down or reconfigured, it may disappear from the kernel and therefore get a new ifindex, just like what this issue tries to handle (but then for the backhaul side rather than bAP).
  - Again, the name of the interface may be changed - although not for bSTA because that is specified explicitly in the wpa_supplicant config.
- Fronthaul/backhaul interfaces managed by agent (slave, i.e. per radio).
  - Basically this corresponds to the VAPs / BSSes.
  - In general, there may be VAPs that are not controlled by MultiAP (locally configured VAPs). These should still be reported in e.g. AP Operational BSS, but are not controlled by Autoconfig.
  - In general, VAPs may be created and disappear independently of prplMesh. For example, due to some error hostapd may remove a VAP's interface (while still keeping its configuration) and then after a while re-create it. I don't know if this happens in practice.

In terms of identifier stability (i.e. this issue), we have two conflicting things. ifindex is not stable because an interface can be deleted and re-created. But ifname is not stable either because interfaces can be renamed. That said, the use case of renaming interfaces is pretty vague, so we could get away with just disallowing it.

If we use ifnames, however, we have the problem that the interface with that name may not actually exist at the time we try to use it. This is handled correctly (I think) in transport because we handle RTM_NEWLINK and RTM_DELLINK messages there. However, is this also handled correctly in the other places that use interfaces? The advantage of an ifindex is that it is really stable: either it is valid and then it points to exactly the interface you meant, or it is no longer valid and then the interface will never again exist so everything referring to it can be cleaned up. The case that it is not valid yet doesn't exist, because you don't have the ifindex if the interface doesn't exist yet.

My intuition is that:
- we should use ifindex, since it's an actual identifier, while the interface name is just a name;
- we should have a single place that monitors RTM_NEWLINK/RTM_DELLINK; it should send out messages to the rest of the system, and the rest of the system should use these messages to be informed of interface state, no direct ioctls.

I haven't completely worked out yet how all of this can fit together, so I think we need to have some discussion about it. My first, incomplete thought goes something like this.
- Transport is configured with a bridge.
- At startup, transport queries RTM to get a list of all interfaces on the bridge (recursively).
- Transport monitors RTM and keeps the list of interfaces up to date.
- All interfaces are kept in "insecure" state.
- When an interface changes, a message is sent (to agent) with ifindex, ifname and MAC (all of this is in the RTM_NEWLINK message, and AFAIU a RTM_NEWLINK will be generated whenever any of these change).
- agent, backhaul manager, etc. use these messages from transport to keep their local list of interfaces up to date. They use ifname to filter the interesting messages. For example, hostapd STATUS command returns an ifname (in the bss[i] field) for each configured VAP (including VAPs not controlled by prplMesh).
- All other communication that needs to specify an interface uses ifindex, not ifname or anything else.
- agent, backhaul manager etc. send a message back to transport to say that an interface (identified by ifindex) is secure

Note that the above is pretty much the opposite of what #1141 does.

**Comment by arnout** [comment]
After a discussion with @tomereli and @vitalybu (and @morantr, @kantera800 and @rmelotte) we came to the following conclusions:
- In practice, ifnames are stable - interfaces can be renamed, but they aren't in practice.
- Except for bind() in the transport, everything else uses ifnames (* see below).
- Thus, it's easiest if we use ifnames everywhere.
- However, it's possible that the same ifname is reused for something else. E.g. after autoconfig renew, a VAP is removed, but manual configuration adds a VAP, then that VAP may have the name that we previously used for the autoconfigured VAP.
- To handle this, the slaves should send messages to the transport to indicate that interfaces are added or removed -> #1157.

We also talked about the Topology Discovery, which should be sent per-interface. To implement that, we should extend the cmdu_tx topic with a field that indicates the interface on which a message should be sent out, and cmdu_rx with a field that indicates the interface on which it was received (#1160).

We also discussed a bit about the "secure" and "insecure" interfaces. In the end it doesn't make much of a difference w.r.t. the ifindex or ifname choice (#1159).

(*) Unfortunately it's not true that everything else uses ifnames. After reviewing the code, it turns out we need ifindexes for:
- All netlink code:
  - bridge manipulation;
  - nl80211 manipulation;
- arp (it uses sendto()).
