### ISSUE TITLE
[BUG] 4.6.3 test fails due to certified equipment

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1338]
**Describe the bug** -
UCC sends association request with missing bssid field to teh client (MarvellSTA).

MarvellSTA (127.0.0.1:9000) ---> sta_associate,interface,mlan0,ssid,Multi-AP-24GC-1,bssid,**N/A**

As a result client fails to associate and the test fails.

logs can be download from nightly run:
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/566944207

## Steps to reproduce

1. run MAP-4.6.3_ETH_FH24 test on testbed (belgium or PTK1)

## observation:
Earlier in the test Agent1  send reply without the bssid field that could be also the problem.
need further investigation .

 MediatekAGT (127.0.0.1:9002) ---> dev_get_parameter,program,map,ruid,0x000000000000,ssid,Multi-AP-24GC-1,parameter,bssid
 MediatekAGT (127.0.0.1:9002) <-- status,COMPLETE,macaddr,**N/A**

when comparing to tests logs that was performed with certified equipment bssid is correctly sent yo the client.
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2FCertified%20Agent%20tests%2FPASS%2FMAP-4.6.3_ETH_FH24G_Nov-27-2019__16-57-36

**Comment by rmelotte** [comment]
It looks like there is a combination of bugs in `cmds/WTS-MAP/CNTLR-DEFAULT-CONFIG-4.6.3.txt` and `cmds/WTS-MAP/4.6.3-BHETH-FHNA-BSSInfoSelect.txt`.
The configuration of the controller is never done (there should be a `dev_set_config` line for the controller):
```
        ~~~~~ Load BSS configuration info to CTT Controller ~~~~~

2020-05-26 03:56:42.378 - INFO - Sleep... 5 seconds
2020-05-26 03:56:47.391 - INFO - 
```

From a comparison with with 4.8.5:
- `cmds/WTS-MAP/CNTLR-DEFAULT-CONFIG-4.6.3.txt` contains lines ending with `ALL-SSID_eq_1!` that configure 2 vaps, so they should instead end with `gt_1`
- `cmds/WTS-MAP/4.6.3-BHETH-FHNA-BSSInfoSelect.txt` should check the MAX_BSSID number and define `!$BSS_Config_Set` accordingly, instead of always setting it for a single vap.

This bug is similar to this one: https://git.prpl.dev/prplmesh/wfa-certification/ucc/-/merge_requests/5

**Comment by Mila-Sh** [comment]
the issue reproduced with all certified equipment
MAUT- Qualcomm, Controller - Marvell, Agent1- Mediatek, STA -MarvellSTA.
There is no loading BSS configuration info to CTT Controller. BSS_Config_Set is equal to 431-ETH-NA

**Comment by ghost** [comment]
4.6.3 is passing in the certification testbed with changes that have been communicated to the WFA certification support team.
We're still waiting for their official OK, but it's looking good
