### ISSUE TITLE
[BUG] start monitor fails if client was associated before prplmesh start 

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#1369]
**Describe the bug** -
Client can be associated before prplmesh is up , in this case association task should start monitoring all already associated clients.
the problem is that start monitoring fails and thus stuck in a loop .

## platform 
UGW

## Steps to reproduce

1. Build
2. associate client 
3. start prplmesh controller/agent
4. See in the logs this and that association task is stuck trying to start monitoring the client .

DEBUG 10:07:29:783 <2002066752> association_handling_task.cpp[405] --> task association_handling id 8: response for start monitoring from 00:e0:92:00:01:47 for sta 86:15:e5:2b:a7:fe timed out! attempts=2
DEBUG 10:07:29:784 <2002066752> association_handling_task.cpp[80] --> task association_handling id 8: START_RSSI_MONITORING
DEBUG 10:07:29:785 <2002066752> association_handling_task.cpp[96] --> START_MONITORING_REQUEST hostap_mac=00:e0:92:00:01:47 sta_mac 86:15:e5:2b:a7:fe
DEBUG 10:07:29:796 <2002066752> association_handling_task.cpp[265] --> task association_handling id 8: **received ACTION_CONTROL_CLIENT_START_MONITORING_RESPONSE, success=false**
WARNING 10:07:30:300 <2002066752> statistics_polling_task.cpp[93] --> task statistics polling task id 1: timeout slave 00:e0:92:00:01:46
DEBUG 10:07:32:827 <2002066752> association_handling_task.cpp[405] --> task association_handling id 8: response for start monitoring from 00:e0:92:00:01:47 for sta 86:15:e5:2b:a7:fe timed out! attempts=4
DEBUG 10:07:32:827 <2002066752> association_handling_task.cpp[80] --> task association_handling id 8: START_RSSI_MONITORING
DEBUG 10:07:32:828 <2002066752> association_handling_task.cpp[96] --> START_MONITORING_REQUEST hostap_mac=00:e0:92:00:01:47 sta_mac 86:15:e5:2b:a7:fe
DEBUG 10:07:32:835 <2002066752> ire_network_optimization_task.cpp[68] --> task hostapd_tx_on_ack - ire_network_optimization id 9: done optimizing network
DEBUG 10:07:32:836 <2002066752> task_pool.cpp[80] --> erasing task hostapd_tx_on_ack - ire_network_optimization, id 9
DEBUG 10:07:32:838 <2002066752> association_handling_task.cpp[265] --> task association_handling id 8: **received ACTION_CONTROL_CLIENT_START_MONITORING_RESPONSE, success=false**

**Comment by itayx** [comment]
I believe the issue rises due to the fact that even though the `ap_wlan_hal_dwpal` detects the
pre-connected clients, they are never added to the `monitor_db`'s `sta_nodes` a map which contains
the connected `STA`s. The `STA`s are not in the `sta_nodes` map because the `monitor_thread` doesn't
receive the `STA_Connected` event when the pre-connected `STA`s are detected.

If the function `ap_wlan_hal_dwpal::generate_connected_clients_events` which detects the
pre-connected `STA`s will sent the `STA_Connected` event to the monitor, it will solve this issue, 
nd will cause the pre-connected `STA`s to be added to the `sta_nodes` map in the `monitor_db`.

@kantera800 What do you think?

Talked with @morantr.
He thinks the best course of action would be to implement a much thinner version of `generate_connected_clients_events` which only generates `Event::STA_Connected` so the client would be present in the `monitor_db`'s `sta_nodes`

**Comment by kantera800** [comment]
I prefer not to change the previous implementation. If this is the way it was working before then sure let's add the event.
 @morantr what do you think

**Comment by itayx** [comment]
After going over the changes made to the association pattern in PR #1289
I believe the issue is caused because the call to `sta_add` was moved from the
ACTION_MONITOR_CLIENT_START_MONITORING_REQUEST handling to the STA_Connected handling, causing
already existing clients to not be added to the `monitor_db`.
Therefore the best course of action would be to add a function called `generate_connected_clients_events` to the `mon_wlan_hal`
In `generate_connected_clients_events` the `mon_wlan_hal_dwpal` would pull the existing clients from the DWPAL using the `STA-FIRST` & `STA-NEXT` commands.
Then for each client send a "STA_Connected" event to the monitor_thread, where they will be added to the DB by the already existing code.
The best location to call the `generate_connected_clients_events` function would be after the `monitor_thread` handles the `ACTION_MONITOR_SON_CONFIG_UPDATE` CMDU.
