### ISSUE TITLE
Create datamodel for interfaces in backhaul thread

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#1462]
Create a datamodel with all the information about interfaces required by backhaul manager. Populate it once and reuse it, instead of fetching such information every time we need it.

For each interface, include its name and MAC address.

Note that we already collect the local interfaces and sent that information to the transport, and that is the way the transport knows which interfaces to listen on. See backhaul_fsm_main, state MASTER_DISCOVERY. Only, that list of interfaces is not stored at the moment.

When the interfaces datamodel is available, refactor all the code that calls `network_utils::linux_get_iface_list_from_bridge`, `network_utils::linux_iface_get_name` and `network_utils::linux_iface_get_mac`. Also refactor code to implement the suggestion made in this [comment](https://github.com/prplfoundation/prplMesh/pull/1458#discussion_r443125476)

**Comment by RanRegev** [comment]
Yes! indeed.
Instead of massing around with data structures, transforming them from one map to the other, from vectors to lists, etc. - build a data structure that reflects reality _as we need it_, having all functionality embedded inside it.
e.g.:
```cpp
class BackhaulStructure{
public:
Socket* get_socket_for_station(const sMacAddr &sta_mac);
template<class First, class Last>
std::vector<sMacAddr> get_common_bssids(First, Last) const;
};
```
The point is to expose interfaces for *what is needed by the backhaul* in such a way that the developer will be able to focus on the logic and not on the technical details of extracting what is needed.
