### ISSUE TITLE
More flexible to parse TLVs in autoconfiguration WSC message.

### ISSUE THREAD

**Issue by steventing** [prplfoundation/prplMesh#160]
Current implementation, the TLVs parsing order when receiving autoconfiguration WSC message is 
- AP Radio Basic Capabilities TLV followed by one WSC M1 **in Controller**
- AP Radio Identifier TLV followed by one or more WSC M2 TLV **in Agent** 

But in the Multi-AP specification v1.0, there seems to be no TLVs order constraint like this. 
For example, if the MAP Controller sends the autoconfiguration WSC message contains 2 WSC M2 TLVs followed by one AP Radio Identifier TLV to the beerocks agent, this cmdu failed be parsed.

**Describe the solution you'd like**
Check whether the mandatory TLVs exist in the certain message format instead of assuming the TLVs order.

**Describe alternatives you've considered**
No

**Additional context**
Just suggest and many thanks

**Comment by arnout** [comment]
This would probably be part of a "tlvf v2" refactoring. Currently, TLVs are supposed to be processed in the order that they appear in the CMDU. "tlvf v2" should allow to search for TLVs of a specific type in the TLV list.

**Comment by tomereli** [comment]
TLVF V2 will certainly aim to solve this so that users will just do a single `parse` which in turn will parse all TLVs it finds. Then the user would call `getClass()` to actually set / read the contents of each TLV.

With the current implementation, user code can just be modified to use `getNextTlvType()` and call the correct `addClass()` each time, till it reaches EOM - so there is no real gap here, just "ugly" code to support all combinations :)

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [tlvList refactoring](https://trello.com/c/JHrwp6IN/19-tlvlist-refactoring)
