### ISSUE TITLE
5.4.3 AP configuration BSS Tear Down

### ISSUE THREAD

**Issue by c0dingn0mad** [prplfoundation/prplMesh#199]
## Description

The prplMesh controller needs to pass the test case as defined in 5.4.3

## Exit criteria

The flow is completed once the controller passes this test in the scenario and testbed described in the upstream definition.

- [ ] #197 
- [ ] #198

**Comment by Mila-Sh** [comment]
MAP-5.4.3_ETH_FH24G fail
MAP-5.4.3_ETH_FH5GL fail
MAP-5.4.3_ETH_FH5GH PASS
commit hash: ba99b55
Configuration as required in test plan v1.0:
MCUT : prplMesh
Agent1 : Marvell-AP
Agent2 : None
CTT STA : None
logs for MAP-5.4.3_ETH_FH5GH : 
https://ftp.essensium.com/owncloud/index.php/s/ketl3eFhIgwcweZ?path=%2Fprpl%20controller%20tests%2FPASS%2FMAP-5.4.3_ETH_FH5GH_PRPLMESH_MARVELL

**Comment by CoralMalachi** [comment]
Currently, test 5.4.3 fails with the following message : 

`Beacon frame found, check CTT Agent1 is not operating on the configured channel`

The UCC tries to validate there are no beacons from that radio, but beacon frame found.
The reason for this is when the UCC sends the command  dev_set_config without SSID argument it means we should tear down the specified radio, but the current implementation does not support it.

The solution is to tear down the radio when the UCC sends the DEV_SET_CONFIG without the SSID parameter, instead of setting the SSID to an empty string. @tomereli
