### ISSUE TITLE
Wrong swapping of CmduMessage::getMessageType()

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#43]
In some cases (unclear when exactly) the transport reports:
```
[transport] [WARNING] ieee1905_transport_local_bus.cpp[84]: CmduTxMessage messageType mismatch
```
This is because the messagetype in the metadata is incorrectly swapped. It gets swapped by ieee1905_1::CmduMessage::getMessageType() in bus_send(), but it shouldn't do any swapping there.

Probably there is some misinterpretation of m_swapped, but we couldn't find out easily.

**Comment by tomereli** [comment]
Not a bug - for `CmduMessageTx`, `m_swap` is always false, but after finalize `m_swapped` is.
Then in the BTL we use `getCmduMessageType()` (which is defined in the base class - `CmduMessage`) to set the metadata for the transport which is not actually needed since the CMDU header already has the correct type already set in network byte order as it should.

The warning, in this case, is OK. We could solve it in multiple methods - for example, moving `getCmduMessageType()` away from the base class and implementing it differently for RX and TX, but it should be part of a much wider change for the TLV factory (changing it to a real serializer-deserializer and only create the output byte stream at the end, while keeping all members always in host byte order).
