### ISSUE TITLE
[Refactor] Agent: single executable per radio

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#435]
## Description

The agent architecture is currently a bit weird. It has an agent process with a main thread that is mostly idle and a backhaul manager thread and a platform manager thread. Then for each radio, there is a separately forked slave, again with a main thread that is mostly idle, and a slave thread and an ap manager thread. Each slave again forks a separate monitor process.

This is too complicated.

In a first step, we want to merge the monitor into the slave, still as a separate thread.

In a second step, we want to connect the slaves directly to the bus. Currently, the backhaul manager is responsible for forwarding some 1905/map messages to the slaves, but they could just as well receive them directly.

In a third step, we want to reduce the number of threads. Since all these threads are listening to sockets, we can have just a single select that monitors all sockets. Only the platform manager may need a separate thread since it has to interact with the platform bus mainloop.

**Comment by morantr** [comment]
I think the first step should moving out the ap_manager thread out to monitor the process, and call it radio manager, which will have to classes inside it: ap_manager and monitor (I really consider to change its name to "measurment_manager").

second, make the son_slave be derived from btl instead of the backhaul_manager, and move out all parts of backhaul_manager that are not related to physical link establishment to the son_slave.
as part of it, change the son_slave name to agent, and run only one instance of it.

third, make the master thread to be derived from btl instead of mrouter, and remove mrouter.
bonus: change thread name to controller :)

I think that the backhaul manager should have a thread of its own since we don't want the agent to be blocked while waiting for some radio operation (like scanning).

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mrouter refactoring](https://trello.com/c/ubEitQl9/3-mrouter-refactoring)

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [mrouter refactoring](https://trello.com/c/6CLMwoNb/6-mrouter-refactoring)
