### ISSUE TITLE
Agent full-duplex with multiple radios

### ISSUE THREAD

**Issue by fgervais** [prplfoundation/prplMesh#442]
I don't know much about easymesh at this point but I have experience with 802.11s so I'm assuming the easymesh agents are a bit like the 802.11s nodes in the way that if they act like a relay/hop, the relaying process is half-duplex.

Does easymesh have support for agents with multiple radios as to relay in full duplex mode?

**Comment by morantr** [comment]
I'm not familiar with 802.11s, but I can say easymesh agent can have multiple radios working in full-duplex.
Please do not open an issue for a questions. For that, you have our slack channel.

**Comment by arnout** [comment]
EasyMesh (and therefore prplMesh) is a misnomer, because it has not much to do with mesh. Multi-AP (like the specification is called) is a better name.

In Multi-AP, the traffic is concentrated over a backhaul link. The backhaul can be wired Ethernet or powerline, or wireless. If it is wireless, it will normally go over a single radio. The repeater will determine by itself which radio to use for the backhaul link, but the controller is able to force it to a specific radio and backhaul AP with the backhaul steering CMDU. 

If the radio which has the backhaul link also has a simultaneous fronthaul AP (i.e., stations can connect to it), then it indeed works in half-duplex. In addition, this forces the fronthaul AP to use the same channel as the backhaul link. Therefore, for proper dual-band full-duplex operation with wireless backhaul, the repeater should have 3 radios: a 2.4GHz radio, a 5GHz radio, and a radio that is reserved for the backhaul link.

**Comment by fgervais** [comment]
Thank you
