### ISSUE TITLE
Do swapping while reading/writing instead of in finalize()/parse()

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#547]
Currently, the tlvf swapping is done in parse() resp. finalize(). This leads to hard-to-understand code and numerous bugs (#33, #43, ...).

It would be better to do swapping immediately when reading/writing the struct, so the struct contents is always swapped.

Also, as observed by @mariomaz, the cost of byte reversal on modern processors is normally negligible. Network Byte Order should always be used for the sake of having a simpler code.

Two possible approaches for fixing this:

- Replace the single `uint16_t& foo()` method with separate `uint16_t foo() const` and `void foo(uint16_t)` methods. This requires updating all setters to be updated, so quite a big change.
- Add a wrapper `template<T> class accessor` that implements `operator T() const` and `T operator =(T)` that do swapping, and generate these as return values for the basic types.

**Comment by tomereli** [comment]
The first suggestion as you say is a huge change, so I think it's off the table unless we have a spare engineer for a month or so :)
TLVF should have been initially designed with this approach though, but now its a bit too late.

The second suggestion is legit, but will also require lots of changes for callers since on many occasions we get the value to a temporary variable and change that variable. This will fail in compilation of course since we return const, so will show us all we need to change..

**Comment by tomereli** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BWL nl80211 implementation](https://trello.com/c/xocDS5qw/23-bwl-nl80211-implementation)
