### ISSUE TITLE
Endless autoconfig search in product 

### ISSUE THREAD

**Issue by mariomaz** [prplfoundation/prplMesh#554]
When the agent boots, it looks for a controller.
In the certification setup, the controller will not answer unless configured to, which may result in the prplMesh agent FSM reset which will stop since `stop_on_failure_attempts` is 1.

In certification, we want the behavior to be different - `stop_on_failure_attempts` should be 0 which will cause the agent to retry onboarding indefinitely.

`certification_mode` parameter must also be moved from BCL configuration to BPL configuration.

A different init script will be used to set this up when in certification mode.

**Comment by tomereli** [comment]
This is relevant for a product. In product mode, we should look for a controller endlessly - so this should be part of milestone 3.

For certification - it is not an issue, cause even if we stop on failure due to a missing controller, the UCC will send a `dev_reset_default` which will restart the agent and make it search for the controller again.
