### ISSUE TITLE
[TASK] Add Runtime raw sockets disable functionality for dwpal

### ISSUE THREAD

**Issue by kantera800** [prplfoundation/prplMesh#590]
Beerocks utilizes RAW_SOCKETS, which is not allowed by default in nwk user used in UGW.
Until this issue #593 is resolved and in order to support repeater mode in UGW but not to break other platforms we need to add functionality that will disable in run-time all raw socket related tasks in case of failure to open raw socket.

PR #639
raw sockets tasks:
- arp monitor
- DHCP monitor 
- TBD

**Comment by arnout** [comment]
I've done a quick check of the use of raw sockets.

```
agent/src/beerocks/monitor/monitor_rssi.cpp:    if ((arp_socket = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ARP))) < 0) {
common/beerocks/bcl/source/network/network_utils.cpp:        if ((arp_socket = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ARP))) < 0) {
```

For these I think it's not appropriate that monitor uses ARP directly. Instead, it should be abstracted in some library, probably bwl. And it should not mention ARP directly - the only goal here is to make sure there is some traffic from the STA so that RSSI can be measured. A radio may have a different way to achieve that.

```
framework/platform/bpl/uci/arp/monitor/arp_monitor.cpp:        if ((arp_socket = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ARP))) < 0) {
framework/platform/bpl/uci/arp/monitor/arp_monitor.cpp:    if ((m_fdMonSocket = socket(AF_NETLINK, SOCK_RAW | SOCK_CLOEXEC, NETLINK_ROUTE)) < 0) {
framework/platform/bpl/uci/arp/monitor/arp_monitor.cpp:    if ((m_fdArpSocket = socket(PF_PACKET, SOCK_RAW, htons(ETH_P_ARP))) < 0) {
```

Why are there two arp monitors?

```
agent/src/beerocks/slave/backhaul_manager/wan_monitor.cpp:    int fd = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
```

I think that everything using netlink should use libnl3 instead of open-coding the netlink stuff, no? In libnl3, this would be hidden in `nl_socket_alloc()`. Is that acceptable for UGW?

Note BTW that a netlink socket is SOCK_RAW, but opening it is non-privileged because the kernel does finer-grain access control based on the individual messages.


```
framework/discovery_agent/topology_discovery_agent_messages.cpp:    if ((sockfd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL))) == -1) {
```

This shouldn't be in discovery_agent at all, it should use the transport. But since this code is not sued for the time being, it should be ignored.

```
framework/transport/ieee1905_transport/ieee1905_transport_netlink.cpp:    int sockfd = socket(AF_NETLINK, SOCK_RAW, NETLINK_ROUTE);
```

Again, should use libnl3.

```
framework/transport/ieee1905_transport/ieee1905_transport_network.cpp:    if ((sockfd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL))) < 0) {
framework/transport/ieee1905_transport/ieee1905_transport_network.cpp:    if ((sockfd = socket(AF_PACKET, SOCK_RAW, htons(ETH_P_ALL))) == -1) {
```

If UGW can't use raw sockets, it can't use the transport.

**Comment by kantera800** [comment]
Its not that UGW cannot use raw sockets, its just  not allowed in nwk user . 
Regarding  ARP monitor, its an old code and you are probably right it belongs in bwl . 
We should open a refactoring task to do that.

**Comment by kantera800** [comment]
done in  #639
