### ISSUE TITLE
Channel selection full flow (agent + controller)

### ISSUE THREAD

**Issue by arnout** [prplfoundation/prplMesh#62]
## Description (Full channel selection flow)
Channel selection is a Multiap core module responsible for selecting AP channels dynamically, using Beerocks and Wi-Fi (WAVE) algorithms, controlling the DFS protocol flows and updating the Beerocks database with relevant channel selection data.

This task will focus on the initial implementation of channel selection task on the Controller side, with no DFS channel support, as described on Multiap standard R1, and include the following sub-tasks:

- [x] 1. Add the operating class table and channel/operating-class converting functions.
- [ ] 2. Disable the old channel selection task from working.
- [ ] 3. Creating a channel selection task skeleton which will include:
    - Create task event types.
    - Create a stub state machine.
    - Create a stub event/response handler (will also include handlers on son_master_thread).
    - Create Task setters/getter on Controller DB.
- [ ] 4. Add an Initiate of a new channel selection task on son_master_thread.
- [x] 5. Add a triggering of Agent channel selection on channel selection task, via BML.
- [x] 6. Add a triggering of Agent channel selection on channel selection task, upon AutoConfig M2 message.

Channel Selection Task Core can be split into the following sub-tasks:
- [ ] 1. Send preference query CMDU.
- [ ] 2. Parse preference query report CMDU.
- [ ] 3. Send channel selection request CMDU.
- [ ] 4. Handle channel selection response CMDU and wait for operating channel report.
- [ ] 5. Parse operation channel report CMDU.
- [ ] 6. Activate Agent on Controller DB.

Channel Selection Task implementation will also include:
- [ ] 1. Increment task state machine.
- [ ] 2. Implement task logic.
- [ ] 3. May require to add setters/getters to Controller DB.

### Exit criteria
To be defined for each sub-task with SPs

### Detailed description
[MultiAP_Channel_Selection_v17.docx](https://github.com/prplfoundation/prplMesh/files/3342757/MultiAP_Channel_Selection_v17.docx) - internal Intel design document:
- [ ] upload the design document to prplMesh github under documentation

- **Problem statement** - Passing easymesh controller certification.
- **Possible solutions** - In order to verify that Channel Selection on Controller works properly, it is needed to test it with a certified Agent. If a certified Agent is not available, implementation on the Agent side may be required. An alternative solution can simply be implementing only the controller side and testing with the testbed setup - this is the preferred approach.
- **Components affected** - controller/common/agent(optional)
- **Build considerations** - None.
- **Dependencies** - None.

**Comment by morantr** [comment]
### Description
Channel selection is a Multiap core module responsible for selecting AP channels dynamically, using Beerocks and Wi-Fi (WAVE) algorithms, controlling the DFS protocol flows and updating the Beerocks database with relevant channel selection data.

This task will focus on initial implementation of channel selection task on Controller side, with no DFS channel support, as described on Multiap standard R1, and include the following sub-tasks:

1. Add operating class table and channel/operating-class converting functions.
2. Disable old channel selection task from working.
3. Creating channel selection task skeleton which will include:
    - Create task event types.
    - Create stub state machine.
    - Create stub event/response handler (will also include handlers on son_master_thread).
    - Create Task setters/getter on Controller DB.
4. Add an Initiate of a new channel selection task on son_master_thread.
5. Add a triggering of Agent channel selection on channel selection task, via BML.
6. Add a triggering of Agent channel selection on channel selection task, upon AutoConfig M2 message.

Channel Selection Task Core can be split into the following sub-tasks:
1. Send preference query CMDU.
2. Parse preference query report CMDU.
3. Send channel selection request CMDU.
4. Handle channel selection response CMDU and wait for operating channel report.
5. Parse operation channel report CMDU.
6. Activate Agent on Controller DB.

Channel Selection Task implementation will also include:
1. Increment task state machine.
2. Implement task logic.
3. May require add setters/getters to Controller DB.

### Exit criteria
TBD

### Detailed description
[MultiAP_Channel_Selection_v17.docx](https://github.com/prplfoundation/prplMesh/files/3342757/MultiAP_Channel_Selection_v17.docx) - internal Intel design document:

- **Problem statement** - Passing easymesh certification.
- **Possible solutions** - In order to verify that Channel Selection on Controller works properly, it is needed to test it with certified Agent. If certified Agent is not available, implementation on Agent side may be required.  
- **Components affected** - controller/common/agent(optional)
- **Build considerations** - None.
- **Dependencies** - None.

**Comment by tomereli** [comment]
@morantr I updated the description with your comment.
This is the BIG task for the whole channel selection activity - we need a very small subset of that for passing certification.

In my view these are the tasks we should start with, according to priority - see https://github.com/prplfoundation/prplMesh/issues/74

**Comment by ghost** [comment]
@arnout @morantr Is this issue still unfinished? If it's finished, please close it.
If it's not yet fully completed, but the missing pieces are not needed for wired certification, please change the milestone.
If any work remains for this milestone, we need to know ASAP

**Comment by arnout** [comment]
Not completed yet, but definitely not M1 material.

Also reassigning to Alex as I believe he was the last one to work on this (DCS context).
