### ISSUE TITLE
[TASK] CI: split certification tests per device

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#759]
## Description

Instead of requiring the users to enter the DUT for each test they want to run, it would be more convenient to have a separate manual job for each device.

## Exit criteria

- There is a separate job to manually run the certification tests with each device.
- The Gitlab schedules can still choose what device to run the tests with

**Comment by rmelotte** [comment]
See also https://github.com/prplfoundation/prplMesh/pull/748#discussion_r371719406 .

**Comment by arnout** [comment]
From :

> I tried something on dev/ci-multiple-duts-merge-scheduled-manual, but for some reason Gitlab marks the pipeline as "blocked" when there are manual, not triggered, jobs and no longer as passing: https://gitlab.com/prpl-foundation/prplMesh/pipelines/113248562

I guess that is because the `when: manual` inside the `rules` section no longer implies the [`allow_failure: true`](https://docs.gitlab.com/ee/ci/yaml/#allow_failure).
That kind of ties in with the [allowed attributes for rules](https://docs.gitlab.com/ee/ci/yaml/#permitted-attributes): `allow_failure` is not one of them...

How about this:

```
.run-certification-tests:
  when: $MANUAL_IF_NOT_SCHEDULED
  variables:
    MANUAL_IF_NOT_SCHEDULED: manual
```
and set MANUAL_IF_NOT_SCHEDULED to always from the schedule.

> Also if we want to split the certification tests between smaller groups, I'm starting to think that it would be simpler to just generate a yaml.

It always comes down to that :-)
