### ISSUE TITLE
tests:test_flow.py:test_channel_selection cover 4.2.1 Certification test

### ISSUE THREAD

**Issue by abelog** [prplfoundation/prplMesh#926]
### Description
`test_flow.py:test_channel_selection` currently sends empty channel selection request. As result - `test_channel_selection` test doesn't verify agent reaction to `CHANNEL_SELECTION_REQUEST_MESSAGE` due to empty payload.
As agent already able to pass 4.2.1 on testbed, we can complete `test_channel_selection`. Thus, `test_flows.py` will cover whole MAP-4.2.1 Certification test scenario.

### Acceptance criteria
* `test_channel_selection` send full payload for `0x8006` command
* `test_channel_selection` verifies that proper channel was selected ( `Operating Channel 
Report` was sent to controller)

**Comment by arnout** [comment]
The check "verifies that proper channel was selected" should have two parts:
- On the agent, check that the radio is actually operating on that channel.
- On the controller, check that the operating channel report was received.

And that last bit again consists of two parts:
- On the controller, check that the operating channel report was received.
- On the agent, check that the ACK was received with the same MID as the operating channel report.

Finally, for these two checks, instead of "on the agent/on the controller", we can also simply check that the message passes on the network - after #924 gets merged.
