### ISSUE TITLE
[BUG] MAP-5.4.1_ETH_FH5GL/GH occasionally fails on master (dummy)

### ISSUE THREAD

**Issue by rmelotte** [prplfoundation/prplMesh#956]
Here is is an example job where it fails:
https://gitlab.com/prpl-foundation/prplMesh/-/jobs/468322587

For what it's worth, it looks like it happens less often when the test is run with the rax40.

The test ends with:
```
 2020-03-11 21:36:56.651 - INFO - SNIFFER (192.168.250.5:9999) ---> sniffer_control_filter_capture,InFile,MAP-5.4.1-STEP13-18_decrypted,OutFile,MAP-5.4.1-STEP13_decrypted,srcmac,00:90:4c:2a:10:0c,destmac,0a:03:7f:58:95:17,framename,assoreq,nframes,1
2020-03-11 21:36:59.467 - INFO - MSG: No Association Request from CTT Agent2 found
```

**Comment by arnout** [comment]
I've been staring at this for a while...

The problem is that the Broadcom agent doesn't succeed in pushbutton onboarding to the Qualcomm agent (after the Qualcomm agent has been configured).

From the wireless sniffer logs, it looks like the Qualcomm agent is configured correctly: it beacons both SSIDs.

But then, when WPS starts, I don't see the Multi-AP subelement in the WPS tag. So it wouldn't do Multi-AP onboarding. I would need to check a pcap of a successful one to be sure though.

**Comment by rmelotte** [comment]
Also happens with 5GH: https://gitlab.com/prpl-foundation/prplMesh/-/jobs/475308333
